### ISSUE TITLE
Enabling sentry-symfony hides deprecation messages

### ISSUE THREAD

**Issue by Epskampie** [getsentry/sentry-symfony#120]
I noticed that enabling this bundle hides symfony deprecation messages.

Steps to reproduce:

* Start a new symfony project (i used symfony 3) `$ symfony new test lts`
* Add a simple deprecated call to `DefaultController`: `$this->getDoctrine()->getEntityManager();`
* Notice there is a deprecation message for this in the web profiler toolbar.
* Now open `AppKernel.php`, and add the SentryBundle (for all environments, not just `prod`)
* Notice the deprecation message is now gone.

I know now that I shouldn't add the SentryBundle in a `dev` environment, but still it would be better if sentry didn't eat those deprecation logs if possible.

**Comment by ragusa87** [comment]
I can confirm this bug using:
- symfony 2.8.40, sentry/sentry-symfony 1.0.2, symfony/monolog-bundle 2.12.1
- symfony 3.4.10, sentry/sentry-symfony 2.0.2, symfony/monolog-bundle 2.12.1

Loading the bundle hide all deprecated messages.
 ```@trigger_error("Test deprecated warning", E_USER_DEPRECATED);```

**Comment by Jean85** [comment]
Sorry that I missed this issue!

Yes, it's not good to use this bundle in dev; also, the issue is not in the bundle in itself but in the underlying SDK; the Sentry client register itself as an error handler, which is probably the same way that Symfony uses to catch the deprecations... so that's probably why we have this bug.

I'm not sure that there is a fix for it... Can you confirm the bug using `sentry/sentry` latest version, 1.9?

**Comment by ragusa87** [comment]
Hello,
Yes, I can confirm that the bug is still there on the latest version of sentry/sentry 1.9 or with dev-master (7bf56a8abc)
I can also confirm you that the raven error handler seems to be the problem, once it is registered, the deprecated messages are hidden (\Raven_ErrorHandler::registerExceptionHandler).
Should we open an issue on the sentry/sentry repository ?

**Comment by Jean85** [comment]
Yes you should, but I don't think you'll find an immediate solution... We should debug how the Symfony handler works and why our handler doesn't pass stuff to him.

**Comment by ragusa87** [comment]
Unfortunately I do not have time to take a deeper look at this yet. However, I opened an issue on sentry: https://github.com/getsentry/sentry-php/issues/605

Thanks for your feedback, and have a nice day.

**Comment by ragusa87** [comment]
@Jean85 I found a workaround ! In the services.yml file, you are calling the Raven_Client's "install" method.
```yml
    sentry.client:
        class: '%sentry.client%'
        arguments: ['%sentry.dsn%', '%sentry.options%']
        public: true
        calls:
            - [install, []]
```
This method register the Raven handlers before the one provided by Symfony and cause the deprecated messages to disappear.
Instead, calling the install method from the "sentry.exception_listener" fix the issue. Because in the meantime, Symfony error handlers are registered (before the raven one).

I have no time for a PR this week but I might be able to help you next week.

**Comment by Jean85** [comment]
Well, if that's the case, maybe just changing the priority of the listener si it will be triggered later should be enough, right? You should be able to do it from the config, can you test it?

**Comment by Jean85** [comment]
Closing this as stale. Feel free to reopen if v3 still has this issue.
