### ISSUE TITLE
Enabling this bundle suppresses errors being logged by symfony and duplicates errors being sent

### ISSUE THREAD

**Issue by ostrolucky** [getsentry/sentry-symfony#156]
Symfony 3.4.14
sentry-symfony 2.0.3
sentry/sentry 1.9.2

enabling this bundle causes errors being sent twice:
![image](https://user-images.githubusercontent.com/496233/44336929-475bd980-a479-11e8-8764-6330b2adc6b8.png)

It also causes errors not being logged in prod.log

**Comment by adsc-cloudtec** [comment]
To avoid the sentry event duplication, you can simply implement an own ExceptionListener that does nothing. Uncaught exceptions will still be logged as sentry events, because they are fatal errors in PHP.

See also #148

**Comment by adsc-cloudtec** [comment]
I have added such an ExceptionListener class in this PR: #163

**Comment by Jean85** [comment]
This double-reporting may stem from the fact that Sentry is wired through two different things:
 * as an error handler, with `Client::install()`
 * with Symfony's error handler

I'm thinking maybe we should migrate away from the first option, to avoid overlapping like this one. But I don't want to introduce BCs. Maybe we can create an option to disable it?

**Comment by Jean85** [comment]
@ostrolucky I'm working on the 3.0 release (which is currently on the master branch) and I've tried removing the listeners to avoid reporting twice, but I'm not reporting anything, since Symfony is catching all exceptions, so nothing hits the Sentry error handler.

How where you able to report the error twice? I need a reproducing case.

**Comment by ostrolucky** [comment]
I no longer have access to project that was using Sentry.

> Symfony is catching all exceptions, so nothing hits the Sentry error handler.

IIRC symfony error handler doesn't just swallow the error, but passes it to other previously registered error handlers, doesn't it?

**Comment by Jean85** [comment]
Sentry's error handler is registered later, so it's him that should get the error and forward to Symfony's. But to me it seems that everything is caught, so no error/exception handler is involved.

**Comment by ostrolucky** [comment]
@martinlutter can you check if this is still a problem in enrola? you still have access

**Comment by martinlutter** [comment]
@ostrolucky errors are still duplicated in Enrola, and on a different project where I've implemented Sentry.
Also the error suppression is still happening, if Sentry is loaded, the default PHP error logging is suppressed completely. So if Sentry can't report the error, there ais no log entry about it anywhere.
I can try to send the code to reproduce later but the implementation is really basic. Maybe worth mentioning that we use Monolog for logging errors locally.

**Comment by Jean85** [comment]
Monolog shouldn't be bothered by Sentry. The Sentry error handler tries to be as transparent as possibile.

I fear that I will have to fall back to using the exception listener again in the 3.0 too, since I don't see the error handler triggered otherwise. But I don't understand how Sentry is getting triggered twice then.

**Comment by Jean85** [comment]
Closing this as stale. Feel free to reopen if this still happens with v3 (beta 2 and newer).
