### ISSUE TITLE
Class aliasing RequestEvent causes incompatibilities with other bundles that detect Symfony versions by checking class existance

### ISSUE THREAD

**Issue by eXtreme** [getsentry/sentry-symfony#307]
So basically it looks like making a class_alias for RequestEvent for Symfony 5.0 compatibility caused my application to break. 

I have SchebTwoFactorBundle in my app which also needs support for 3.4/4.4/5.0 versions and uses an approach of having a main listener with RequestEvent and a Legacy Listener with GetResponseEvent. It uses the legacy listener when RequestEvent class does not exist (see: https://github.com/scheb/two-factor-bundle/pull/233/files#diff-d45aea21a8ed2417fbab0229857c370aR107). However, when combined with SentryBundle 3.3.0+ this class now exists because it has been class_aliased in two files actually (RequestListener.php and SubRequestListener.php). 

I asked about it on Symfony Slack's #support and several users pointed out that it is the SentryBundle that should fix it's compatibility with different events by doing similar thing to TwoFactorBundle which is to have a legacy listener that uses GetResponseEvent.

And I guess other class aliases I've seen in the PR may break other bundles that detect Symfony versions by checking if a new class exists.

For now I've downgraded the bundle to 3.2.1.

**Comment by Jean85** [comment]
I didn't considered this side effect, you're right. We should fix it in that way.

**Comment by scheb** [comment]
I was just about to create a PR for https://github.com/scheb/sentry-symfony/commit/257eb23d6da1d062f411eca1847cdfebe12ccdf0 when I've seen that you've already fixed it. A user of my bundle pointed out the issue (https://github.com/scheb/two-factor-bundle/issues/263).

I basically followed the approach from FriendsOfSymfony/FOSHttpCacheBundle, they're creating a "proxy alias" in their own namespace which points to either the one or the other class. https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/master/src/EventListener/UserContextListener.php#L31-L37

Maybe you like that approach more. But I guess since you already have a working solution you're going to keep it ;)

**Comment by Jean85** [comment]
That's a really interesting approach, and it would also probably make PHPStan happy too! I'll try that out.

**Comment by Jean85** [comment]
This was solved in 3.4.1 (and bugfixed in 3.4.2)
