### ISSUE TITLE
Handle default release version w/o git SHA gracefully

### ISSUE THREAD

**Issue by simonihmig** [getsentry/sentry-symfony#323]
When there is no `.git` data available (e.g. docker setup with only a subfolder of the repo as the shared volume), the version of the root package used for the `release` tag is returned as something like `1.0.0@`.

As suggested in https://github.com/Ocramius/PackageVersions/issues/119, `$version->getPrettyVersion()` of https://github.com/Jean85/pretty-package-versions could be used instead to handle this gracefully.

This is currently not just a "cosmetic" issue, as the sentry frontend seems to not handle this correctly: https://github.com/getsentry/sentry/issues/17474

**Comment by Jean85** [comment]
`Jean85/pretty-package-versions` is already a dependency here, so I don't see any downside here! I'm not sure about the actual behavior here though, because the lack of `.git` folder may spit out a bad version anyway...

Are you willing to write the PR and test it out yourself? I will handle any issue on the dependency if any arise.

**Comment by simonihmig** [comment]
> Are you willing to write the PR and test it out yourself?

Would love to, but not sure how soon that can be. Pretty packed with work and my own open source "duties" :wink:

**Comment by Jean85** [comment]
#325 should resolve this.
