### ISSUE TITLE
If the sentry server is not available, the application throw an error 500

### ISSUE THREAD

**Issue by galphanet** [getsentry/sentry-symfony#324]
Effect: If the sentry server is not available, the symfony application throw an error 500 (fail close).
How to reproduce: make the sentry server unavailable (shutdown it, firewall it, /etc/hosts to 127.0.0.1)

The error message we see in the logs is:
`
PHP message: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in .../vendor/php-http/curl-client/src/MultiRunner.php on line 87" while reading response header from upstream, client: xxx server: yyy, request: "GET / HTTP/1.0", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "yyy"
`
Desired effect: If the sentry server is not available, the application should still be available (fail open).

**Comment by stayallive** [comment]
We quite recently enforced better timeouts to hopefully solve these issues.

> https://github.com/getsentry/sentry-php/pull/979

Please make sure the Sentry SDK is installed on version `2.3.2`. You can check this by running `composer show sentry/sentry` and you should see `versions : * 2.3.2`. If not please run `composer update` and check if this still happens when `sentry/sentry` is on version `2.3.2`.

(`sentry/sentry` is a dependency of `sentry/sentry-symfony` so it's not listed in your `composer.json` directly)

**Comment by galphanet** [comment]
Thanks, we have version 2.2.2 so we'll try to update it and test again.

**Comment by Jean85** [comment]
Closing as stale. Feel free to reply or reopen if you still have issues.
