### ISSUE TITLE
Trusted proxies settings are not respected

### ISSUE THREAD

**Issue by Jean85** [getsentry/sentry-symfony#328]
I've found that, due to https://github.com/getsentry/sentry-php/pull/945, trusted proxies headers are no longer fetched; well, to be fair it was neither before, but they were trusted all the time, which is a security mistake.

We need to fix this in the bundle, but I think I'll wait the release of https://github.com/getsentry/sentry-php/pull/984, so we could directly inject the Symfony request instead, just before bridging it to a PSR-7 one using https://symfony.com/doc/current/components/psr7.html

**Comment by ste93cry** [comment]
This should have been fixed in #361 

>they were trusted all the time, which is a security mistake.

I don't think it was a security issue because we're just collecting this kind of information for data analysis 👍

**Comment by ste93cry** [comment]
I'm reopening this because I just realized that the `RequestIntegration` integration has no way to fetch the client IP besides reading it from the `REMOTE_ADDR` server param, so this issue is still not resolved yet. To be honest, I don't have a clear idea of how to make it work without either changing the main SDK or rely on a custom integration for this project because the PSR standard does not offer any method to get specifically the IP address regardless of where it is read from

**Comment by Jean85** [comment]
Wait, we need to split the stuff in two: client and host. We shouldn't confuse the two, even if both are influenced by proxy headers.
