### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by thomaspicquet** [getsentry/sentry-symfony#330]
Hey,
Could you push a new release so we can start using Sentry with messenger?
Thank you!

**Comment by Jean85** [comment]
As said in https://github.com/getsentry/sentry-symfony/pull/326#issuecomment-603492501, I would like to add #322 to the next (3.5) release too, so that's the blocker.

**Comment by X-Coder264** [comment]
@Jean85 It has been over a month since #326 was merged. Can you please consider to tag the new version as soon as possible? We are introducing Messenger in our app and we'll have to basically copy the entire #326 code in our app if this doesn't get tagged soon.

I don't see anything that would stop you from tagging 3.5.1 or 3.6 immediately after #322 gets merged so it doesn't make sense IMO to delay tagging 3.5.0 any longer.

**Comment by Jean85** [comment]
You can fork the repo and merge it on your side if you want to have both PRs active. I've refrained to go forward because [a Symfony maintainer pointed to me the fact that I should change the approach on how this bundle works](https://github.com/symfony/symfony/issues/36472#issuecomment-616210651), so I'm trying to understand how to proceed.

**Comment by X-Coder264** [comment]
Ok, thank you for the fast response.

**Comment by Jean85** [comment]
3.5.0 has been released with #326. 3.5.1 is coming with some fixes, #339 and #340.
