### ISSUE TITLE
Get sentry sdk version is called two times

### ISSUE THREAD

**Issue by dannyvw** [getsentry/sentry-symfony#332]
Getting the sdk version from composer is now performed twice. In our situation this costs unnecessary resources. See blackfire profile image below.

1. https://github.com/getsentry/sentry-symfony/blob/master/src/DependencyInjection/ClientBuilderConfigurator.php#L13
2. https://github.com/getsentry/sentry-php/blob/master/src/ClientBuilder.php#L101

![sentry-get-version](https://user-images.githubusercontent.com/1218389/79865969-56c4c000-83dc-11ea-8159-bae1f7bac7d9.png)

**Comment by Jean85** [comment]
The issue here is the fact that you have something broken in your underlying dependency. 

`PrettyVersions` relies on https://github.com/Ocramius/PackageVersions/. That package normally writes a PHP class during `composer install` with a list of constants containing all the versions for all the installed dependencies; so, that goes straight to opcache, making it blazing fast.

Instead, in your case, your app is relying on `FallbackVersions`, which does a live `json_decode` of your `composer.json`, adding disk I/O on top, so hence the slowness.

You should check your deploy procedure to understand why `FallbackVersions` is kicking in. Normally it happens when you launch your deploy with `composer install --no-scripts`, skipping that passage.

**Comment by dannyvw** [comment]
@Jean85 Yes, i need to check that. But `getVersion` is also called twice, i think that is not needed?

**Comment by Jean85** [comment]
It would be really fast, from memory. 
The multiple calls are probably due to other usages instead, like the base SDK or the `ModulesIntegration`, which report dependencies versions alongside with the event to Sentry.

**Comment by dannyvw** [comment]
See the links in the issue where the getVersion is called. We can close this issue if we dont want to change this.

Composer is an issue in our project. Thanks for the information.

**Comment by Jean85** [comment]
As I said, it's called in two very different places, one in the bundle, one in the base SDK, retrieving versions for the two packages.

**Comment by dannyvw** [comment]
I see, sorry.

**Comment by dannyvw** [comment]
I see, was looking to the wrong names. Sorry.
