### ISSUE TITLE
getSdkVersion() should contain hardcoded version in releases

### ISSUE THREAD

**Issue by alcohol** [getsentry/sentry-symfony#358]
I'm trying to understand why the version isn't simply hardcoded in releases. `Jean85\PrettyVersions::getVersion` (and ultimately `json_decode`) has quite a performance hit for something as simple as returning a version number that should be known at release compile time and can thus be hardcoded IMHO.

Any specific reason why this isn't the case?

Alternatively, is there a way to not lookup this version number until a request actually has to be submitted to Sentry? Cause right now it seems to be looked up on every request our application serves, even if nothing gets reported to Sentry.

**Comment by Jean85** [comment]
`Jean85\PrettyVersions` is leveraged to avoid hardcoding that, since it would be pretty easy to make a mistake and forget to update that, at each release (and in fact it happened multiple times in the past); it also makes possible to report versions of all dependencies, using `ModulesIntegration`.

Anyhow, `Jean85\PrettyVersions::getVersion` shouldn't have performance impacts, because it normally reads a constant from a generated PHP file, which should go straight in opcache, making it a full in-memory operation. If that's not the case, you're probably deploying with `composer install --no-scripts` or some other block that's preventing the generation of such file; in that case, a fallback takes place, which does touch `composer.lock` or `installed.json`, which may slow down execution.

**Comment by alcohol** [comment]
Interesting, I'll look into our deployment pipeline to see if that is indeed the case. Thanks for the tip.

**Comment by alcohol** [comment]
This was indeed the case. I think this issue can be closed. Perhaps you may consider adding an FAQ item or note somewhere to highlight this?

**Comment by Jean85** [comment]
Happy to see it solved.

As for the FAQ, we may add it, but it's 3 levels-of-deps down, and it will disappear with Composer 2, so I don't know if it's worth it... Feel free to send a PR if you will.

**Comment by alcohol** [comment]
Fair enough. Thanks for the swift reply and helpful information!
