### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by shyim** [getsentry/sentry-symfony#364]
Problem 1
    - sentry/sentry-symfony 3.5.2 requires php ^7.1 -> your PHP version (8.0.0-dev) does not satisfy that requirement.

**Comment by W0rma** [comment]
@Jean85 Can we drop older PHP versions - at least for master? This would it make easier to move to PHPUnit 9 which supports PHP 8. Which PHP versions can be dropped? Only 7.1 or 7.2, too since it will reach EOL very soon?

**Comment by shyim** [comment]
I use it already in prod with PHP 8. Had no trouble so far 😅

**Comment by Jean85** [comment]
We should definitely drop 7.1 in master, since it's not supported by the 3.0 SDK: https://github.com/getsentry/sentry-php/blob/b77ff3783060ce3213011ddae369e550ec985dc8/composer.json#L23

cc @ste93cry

**Comment by stayallive** [comment]
I wanted everyone reading to know that this is currently blocked by getsentry/sentry-php#1087, it's being worked on!

**Comment by p-romain** [comment]
Hi, getsentry/sentry-php#1087 is merged, supporting PHP 8 on this package could now be done.

**Comment by JellyBellyDev** [comment]
Go go go php8 compatibility!!! 🚀

**Comment by Yozhef** [comment]
https://github.com/getsentry/sentry-symfony/pull/394

**Comment by Bilge** [comment]
Also waiting on this.

**Comment by Jean85** [comment]
Please note: this is slated for the 4.0 release, which still has a lot of work still pending: https://github.com/getsentry/sentry-symfony/milestone/8

This is due to the fact that getsentry/sentry-php#1087 will be released in 3.x, which will be supported by our future 4.0 only.

Also, we're currently having issues with the build, with unexpected PHPStan failures in #400
If anyone could help us there, we could ship this faster!

**Comment by Bilge** [comment]
Whilst I understand the next major version will support PHP 8, it would greatly ease upgrading if the 3.x branch also supported PHP 8. If it technically does already, adding the tag should be trivial. Having the tag means users can upgrade to PHP 8 and later upgrade sentry-symfony, instead of having to do both at the same time. Therefore having a stable PHP 8 tag now is important, rather than waiting for sentry-symfony 4 release.

**Comment by ste93cry** [comment]
>it would greatly ease upgrading if the 3.x branch also supported PHP 8

Unfortunately PHP8 is supported only starting from `getsentry/sentry-php` `3.0`, and there have been some breaking changes that must be handled to consider supporting that version. To be honest, we don't have the time and capacity to do the work for both the old and the new version as the codebase already started diverging and I'm not sure how much time consuming would be to keep both branches in sync. If you absolutely need to do the upgrade to PHP8, please consider using the plain SDK and instantiate it manually as it's unlikely the new version of this bundle will come before the next year

**Comment by Wirone** [comment]
I was able to upgrade project to PHP8 using forks:

```
{
    "repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:Wirone/sentry-symfony.git",
            "info": "In order to get PHP8 support"
        },
        {
            "type": "vcs",
            "url": "git@github.com:Wirone/sentry-php-sdk.git",
            "info": "In order to get PHP8 support"
        },
        {
            "type": "vcs",
            "url": "git@github.com:Wirone/sentry-php.git",
            "info": "In order to get PHP8 support"
        }
    ],
    "require": {
        "php": ">=8.0",
        "sentry/sentry": "dev-2.x-php8@dev",
        "sentry/sdk": "dev-2.x-php8@dev",
        "sentry/sentry-symfony": "dev-php8@dev"
        ...
    }
}
```

After that I've tested integration and errors were properly reported to Sentry. All I've done in the forks was adding `|| ^8.0` to PHP requirement, so IMO @ste93cry is wrong about PHP8 support, it could be provided in `2.x` branches. Looking at the [list of breaking changes](https://stitcher.io/blog/new-in-php-8#breaking-changes) Sentry packages probably won't be affected and code should be PHP8-compatible.

Please consider releasing `2.x` versions with `|| ^8.0`.

PS. Anyone interested in using Sentry with PHP8 can use my forks, I'll keep them for some time because I'll use them in my current project. But do it on your own responsibility :wink:

**Comment by ste93cry** [comment]
>@ste93cry is wrong about PHP8 support, it could be provided in `2.x` branches
>Please consider releasing `2.x` versions with `|| ^8.0`.

I'm sorry if the message that passed when I wrote my comment was that `2.x` cannot support PHP8 due to breaking changes of the programming language, but it wasn't what I meant: what I meant is that `2.x` and `3.x` branches are different (even if they are not two completely different versions), and although it would indeed be possible to support both, we don't have neither the number of people willing to do it nor the time to do it. We know that `2.x` is still a good version, battle tested and widely used and thus we are committed to keep fixing bugs when they are found, but there is no plan to develop new features for it (which includes also making the necessary changes to build, test and maintain that version on PHP8). If you want to maintain a fork of that version compatible with newer PHP versions feel free to do it, just watch out because there have been some little changes here and there in the codebase to make the code compatible with PHP8, for example getsentry/sentry-php@63c3e72.

Regarding this package instead (the Symfony integration), as you can see we are almost rewriting it from scratch for the `4.x` version and this is taking more time than expected. I am the first person that would like to see it released asap so that I can update my projects to PHP8 too, but I wanna honestly take the time to do the things at my best. As a personal opinion, because I used this bundle but never really bothered about the source code before recent times, I strongly believe that there are a lot of things that can be improved, but doing it means that the BC must be broken, unfortunately, and we don't have such occasions very often because releasing major versions too often would just cause a lot of troubles for people that cannot keep up.

Just as a conclusion, I know people are waiting for this bundle to be compatible with both PHP8 and `getsentry/sentry-php:3.x` and I'm doing my best to finish making the minimum subset of changes I have in mind for the next major version. The plan is to release the next version in the early weeks of the next year, hopefully.

**Comment by Jean85** [comment]
Closing this as it has been implemented in #399.

I completely support @ste93cry stance; we hope to release 4.0 with all the new goodies in the next few weeks, you can keep track of our progress following the milestone: https://github.com/getsentry/sentry-symfony/milestone/8

**Comment by Wirone** [comment]
Regarding to my [previous comment](#issuecomment-752125475) it's now possible to use Sentry on PHP8 with using only 1 fork (instead of 3 as before):

```
{
    "repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:Wirone/sentry-symfony.git",
            "info": "In order to get PHP8 support"
        }
    ],
    "require": {
        "php": ">=8.0",
        "sentry/sentry-symfony": "dev-php8@dev"
        ...
    }
}
```

Forked `sentry/sentry-symfony` now requires `sentry/sdk: ^3.1` which supports PHP8.

:warning: Use at your own risk. I've tested basic integration with `sentry:test` command and will use it for own further development, but as it was mentioned before in v4 branch some alignments could be done for better PHP8 support.

Hopefully v4 will be released soon and forks wouldn't be required to work with PHP8 :slightly_smiling_face:

**Comment by ste93cry** [comment]
>Regarding to my previous comment it's now possible to use Sentry on PHP8 with using only 1 fork

Since `master` on this repo is fully working and PHP8 compatible, what's the reson to use the fork rather than it?

**Comment by Wirone** [comment]
@ste93cry It's only alternative - using fork is *theoretically* safer since it's based on stable version, but can have drawbacks since there is only Composer constraint changed without adjusting code. I would recommend using `dev-master` with exact commit hash to minimize risk of updating to unstable version.

**Comment by RobinHoutevelts** [comment]
Seems 4.0.0 _just_ got released.

So you can all update your composer.json files 😁

**Comment by bitgandtter** [comment]
Any news on a release that supports php8?

**Comment by Yozhef** [comment]
@bitgandtter version 4.0 is support php 8.0
