### ISSUE TITLE
Enable/Disable sentry via configuration

### ISSUE THREAD

**Issue by tristanbes** [getsentry/sentry-symfony#38]
Hi,

Currently, there's no option to disable the bundle

So our local tests and our Travis builds are sending exception to Sentry that are useless

Why not provide a configuration option like http://symfony.com/doc/current/components/config/definition.html#optional-sections ?

**Comment by Addvilz** [comment]
You can do this by not setting the DSN option in these environments.

**Comment by tristanbes** [comment]
Thanks for your reply,

I think this should be mentionned in the README something like
"If the DSN entry is left empty, it will disable sentry"

**Comment by ryabenko-pro** [comment]
With all the respect, adding an option and two lines of code will make it looks better. 
Disabling plugin and removing DSN options are two different actions. This is not explicit and actually not correct, since no one will remove the string but comment it, which makes config file messy.
My car has neutral gear and I can use it when I want engine on, but car not moving. Highly recommended.

**Comment by Addvilz** [comment]
@ryabenko-pro hey, I never said it's a good way to do it :) But it's the one chosen by core devs apparently, and works in the same manner for all SDK's, so if not very sensible, it's at least consistent. I would prefer option to disable as well, however... See #21

**Comment by ryabenko-pro** [comment]
@Addvilz, thanks! I'll address this message there then.
