### ISSUE TITLE
Way to disable ConsoleCommandListener from sending the event to Sentry

### ISSUE THREAD

**Issue by simPod** [getsentry/sentry-symfony#424]
This bundle hooks in `Sentry\SentryBundle\EventListener\ConsoleCommandListener::handleConsoleErrorEvent` as `console.error` listener and sends event to Sentry in `handleConsoleErrorEvent()`.

However, I also send the event through `Symfony\Component\Console\EventListener\ErrorListener::onConsoleError` where my Monolog is hooked in.

This results in event being sent twice. Once by `php` logger (ConsoleCommandListener) and once by `monolog.console` logger. I want to keep only monolog as I do additional record processing there.

How to stop Sentry bundle from hooking into my listeners stack / from sending the event?

I guess I somehow need to deregister this service

```xml
        <service id="Sentry\SentryBundle\EventListener\ConsoleCommandListener" class="Sentry\SentryBundle\EventListener\ConsoleCommandListener">
            <argument type="service" id="Sentry\State\HubInterface" />

            <tag name="kernel.event_listener" event="console.command" method="handleConsoleCommandEvent" priority="128" />
            <tag name="kernel.event_listener" event="console.terminate" method="handleConsoleTerminateEvent" priority="-64" />
            <tag name="kernel.event_listener" event="console.error" method="handleConsoleErrorEvent" priority="-64" />
        </service>
```
------------------
**Though there's one more thing.**

`ConsoleCommandListener` adds exit code to the scope, which is valuable information.

`$scope->setTag('console.command.exit_code', (string) $event->getExitCode());`

I'd like to keep that. Basically allowing not to `captureException` to the hub would do the trick.

```diff
/**
 * This listener handles all errors thrown while running a console command and
 * logs them to Sentry.
 */
final class ConsoleCommandListener
{
    /**
     * @var HubInterface The current hub
     */
    private $hub;

    /**
     * Constructor.
     *
     * @param HubInterface $hub The current hub
     */
    public function __construct(HubInterface $hub)
    {
        $this->hub = $hub;
    }

    /**
     * Handles the execution of a console command by pushing a new {@see Scope}.
     *
     * @param ConsoleCommandEvent $event The event
     */
    public function handleConsoleCommandEvent(ConsoleCommandEvent $event): void
    {
        $scope = $this->hub->pushScope();
        $command = $event->getCommand();

        if (null !== $command && null !== $command->getName()) {
            $scope->setTag('console.command', $command->getName());
        }
    }

    /**
     * Handles the termination of a console command by popping the {@see Scope}.
     *
     * @param ConsoleTerminateEvent $event The event
     */
    public function handleConsoleTerminateEvent(ConsoleTerminateEvent $event): void
    {
        $this->hub->popScope();
    }

    /**
     * Handles an error that happened while running a console command.
     *
     * @param ConsoleErrorEvent $event The event
     */
    public function handleConsoleErrorEvent(ConsoleErrorEvent $event): void
    {
        $this->hub->configureScope(function (Scope $scope) use ($event): void {
            $scope->setTag('console.command.exit_code', (string) $event->getExitCode());
-
-            $this->hub->captureException($event->getError());
        });
    }
}
```

**Comment by simPod** [comment]
I guess that `ConsoleCommandListener` is not intended to send the event.

`ErrorListener` is intended for that which can be successfully disabled through `register_error_listener: false`

**Comment by ste93cry** [comment]
>I guess that `ConsoleCommandListener` is not intended to send the event.

When I refactored the class, I indeed did not take into account the fact that Symfony already hooks into the same event to log the error to Monolog. The old version of the bundle was logging the error through the `ErrorListener` listener, but I moved the event handler in the `ConsoleCommandListener` because my thoughs were that it belonged to the concept of "console" rather than to a "generic error handler". This assumption is clearly leading to the issue you are experiencing, and for solving it I see two ways:

- We move the `captureException()` function call back in the `ErrorListener` listener, which can be disabled through the bundle's configuration
- We make the `captureException()` function call enableable through a constructor argument of the `ConsoleCommandListener` class

I don't have a strong opinion on which way would be more correct or the right solution, however I have many doubts about moving the error handling of the console out to a listener than knew nothing about the [`Console`](https://symfony.com/doc/current/components/console.html) component until this moment. If I had to decide by the way, I would probably prefer to go with the 2nd solution: the value of the new argument can be set through the service container based on the register_error_listener configuration option. @Jean85 WDYT?

**Comment by Jean85** [comment]
I'm of the opposite opinion, because it would work better in the future, when doing #337: we would remove the `ErrorListener` while keeping the others to enrich events.

**Comment by ste93cry** [comment]
After thinking again about the proposed solutions, the first one isn't doable because of BC: we would anyway have to keep calling `captureException()` in `ConsoleCommandListener`, otherwise people that disabled `ErrorListener` will suddenly stop capturing errors. In turn, not making that call configurable will report double errors for people that do use either both listeners, or the console listener and Monolog
