### ISSUE TITLE
Argument 3 passed to Jean85\Version::__construct() must be of the type string, null given, called in /code/vendor/jean85/pretty-package-versions/src/PrettyVersions.php

### ISSUE THREAD

**Issue by YuriyChmil** [getsentry/sentry-symfony#435]
### Environment

Sentry package 4.0.1
Symfony 5.2.1
Composer 2.0.8
PHP  7.4.14

### Steps to Reproduce

composer require sentry/sentry-symfony

### Expected Result

Successfully installed package, and see exceptions in sentry 

### Actual Result

Argument 3 passed to Jean85\Version::__construct() must be of the type string, null given, called in /code/vendor/jean85/pretty-package-versions/src/PrettyVersions.php

**Comment by Jean85** [comment]
Can you post the stack trace of the error? I'm pretty sure that that error is not originating from Sentry itself, but from other packages that are leveraging PrettyVersion.

Also, can you try it again anyway? PrettyVersion now has a 2.0.1 patch that should throw an exception with a more helpful message.

**Comment by YuriyChmil** [comment]
`  - Configuring sentry/sentry-symfony (>=3.0): From github.com/symfony/recipes-contrib:master
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  TypeError {#6577
!!    #message: "Argument 3 passed to Jean85\Version::__construct() must be of the type string, null given, called in /code/vendor/jean85/pretty-package-versions/src/PrettyVersions.php on line 30"
!!    #code: 0
!!    #file: "./vendor/jean85/pretty-package-versions/src/Version.php"
!!    #line: 23
!!    trace: {
!!      ./vendor/jean85/pretty-package-versions/src/Version.php:23 { …}
!!      ./vendor/jean85/pretty-package-versions/src/PrettyVersions.php:30 { …}
!!      ./vendor/jean85/pretty-package-versions/src/PrettyVersions.php:41 { …}
!!      ./vendor/sentry/sentry-symfony/src/DependencyInjection/Configuration.php:76 { …}
!!      ./vendor/symfony/config/Definition/Processor.php:50 { …}
!!      ./vendor/symfony/dependency-injection/Extension/Extension.php:111 { …}
!!      ./vendor/symfony/http-kernel/DependencyInjection/ConfigurableExtension.php:35 { …}
!!      ./vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php:76 { …}
!!      ./vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php:39 { …}
!!      ./vendor/symfony/dependency-injection/Compiler/Compiler.php:91 { …}
!!      ./vendor/symfony/dependency-injection/ContainerBuilder.php:736 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:541 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:780 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:121 { …}
!!      ./vendor/symfony/framework-bundle/Console/Application.php:168 { …}
!!      ./vendor/symfony/framework-bundle/Console/Application.php:74 { …}
!!      ./vendor/symfony/console/Application.php:166 { …}
!!      ./bin/console:43 {
!!        › $application = new Application($kernel);
!!        › $application->run($input);
!!        › 
!!        arguments: {
!!          $input: Symfony\Component\Console\Input\ArgvInput {#5 …}
!!        }
!!      }
!!    }
!!  }
!!  2021-02-03T08:16:51+00:00 [critical] Uncaught Error: Argument 3 passed to Jean85\Version::__construct() must be of the type string, null given, called in /code/vendor/jean85/pretty-package-versions/src/PrettyVersions.php on line 30
`

**Comment by Jean85** [comment]
Ok, so it is really coming from Sentry, precisely from here: https://github.com/getsentry/sentry-symfony/blob/24b1dace366127a665b1cd1f6ed53e7dc2921ead/src/DependencyInjection/Configuration.php#L76

`PrettyVersions::getRootPackageVersion()->getPrettyVersion()` means that it can't retrieve the version of your own project, which seems very strange to me... Are you doing something strange at that level? What's the name that you assigned to your project in your `composer.json`? Is it possible that it's colliding with some of your dependencies? Could you open your `InstalledVersions` class and paste the content of `$installed['root']`?

In the meantime I've opened https://github.com/Jean85/pretty-package-versions/issues/33 to implement a workaround for this.

**Comment by odolbeau** [comment]
Hello!

I have the same problem in different projects, all using:
```
jean85/pretty-package-versions          2.0.1
sentry/sdk                              3.1.0
sentry/sentry                           3.1.4
sentry/sentry-symfony                   4.0.1
```

This is only proprietary projects which don't have any version defined.
Here is what can be found in `$installed['root']`:
```
  'root' => 
  array (
    'pretty_version' => '1.0.0+no-version-set',
    'version' => '1.0.0.0',
    'aliases' => 
    array (
    ),
    'reference' => NULL,
    'name' => '__root__',
  ),
```

**Comment by Jean85** [comment]
Ouch, you have `null` in `reference`? How's that? Are you missing the git repo folder or executable?

Opened https://github.com/Jean85/pretty-package-versions/issues/34 to check it too.

**Comment by odolbeau** [comment]
Regarding your question, I'm not **missing** anything but all mentioned projects are in a monorepo. :)

**Comment by Jean85** [comment]
Oh ok, so the use case is that Composer can't match 1:1 the git repo to the root project, got it.

`jean85/pretty-package-versions` 2.0.2 is out, try again, it should solve all your issues!

**Comment by odolbeau** [comment]
Thanks,  it does! Even if I don't understand why you didn't merge / comment on https://github.com/Jean85/pretty-package-versions/pull/35 :thinking:

**Comment by DeyV** [comment]
Jean85  fix is nicer :)

**Comment by odolbeau** [comment]
Is it an argument to totally ignore a PR, rewrite the code and push it directly on the main branch without even making another PR or mentioning the previous one?

When an external contributor takes time to comment an issue he encountered and takes even more time to propose a fix, the **least** you can do is commenting its PR.

TBH, this kind of behavior **disrespectful** and **toxic**.
Disrespectful because you literally don't care (to stay polite) about the time I took to improve (or try to) your library. Don't worry, I saw you already did this in the past before contributing that's why I'm not surprised.
But it is toxic for the whole open source: I'm king of used to contribute to public repositories and your behavior won't prevent me to continue (well, except for your repository ofc) but what about newcomers? When your first contribution is simply ignored, why would you propose something else?

Please, next time someone contribute to one of yours repositories (no matter how): thanks this person and provides help instead of disregard.

**Comment by ste93cry** [comment]
Folks, calm down as the last thing the opensource community needs is yet another too-heated discussion. I'm pretty sure @Jean85's intention wasn't at all to disgreard any contribution. If you take a look at the time both the issue and the PR have been created by both of you, you may notice that just a few minutes passed between yours and Alessandro's one, so I strongly believe that it simply happened that he did not notice that there was already an existing bugfix and he simply went straight on with his.

Also, I want to point out that as far as I know @DeyV is **not** associated in any way with this package nor the `Jean85/pretty-package-version` package, so his comment, although it may sound disrespectul and toxic (and maybe it is, I don't want to go into the matter), is not representative of either what happened nor what @Jean85's opinion is.

**Comment by Jean85** [comment]
Yeah, sorry for the confusion but yes, it just happened that I missed the notification about your PR, @odolbeau. I even reached this comment just because of that. I can assure you that there was no ill intent on my side, sorry if at the end this came out as rude to you.

I would've declined it by the way, because it's a breaking change for users, and I would've just pushed the issue down the river by pushing the `null` to end users, possibly causing a crash on their end.

I'm anyway happy that the original issues are now solved, so I'll be closing this because of that; but feel free to reply further if you want, I will not lock the conversation (THAT would be absolutely rude!).
