### ISSUE TITLE
bundle monolog configuration is not available on v4.0.0+

### ISSUE THREAD

**Issue by douglasjam** [getsentry/sentry-symfony#438]
All the documentations mention an option "monolog" under sentry inside the bundle configuration, but since v4 it's not available anymore.

`
sentry:
    register_error_listener: false # Disables the ErrorListener
    monolog:
        error_handler:
            enabled: true
            level: error
`

ERROR
`
  Unrecognized option "monolog" under "sentry". Available options are "dsn", "messenger", "options", "register_error_listener".  
`

Missing config
` https://github.com/getsentry/sentry-symfony/blob/4.0.1/src/DependencyInjection/Configuration.php `

**Comment by douglasjam** [comment]
this doc is also outdated
https://docs.sentry.io/platforms/php/guides/symfony/config/

**Comment by Jean85** [comment]
The general docs need to be updated, since the 4.0 release was just 3 weeks ago.
All information regarding the differences are already listed in https://github.com/getsentry/sentry-symfony/blob/master/UPGRADE-4.0.md.

Closing this as I've opened https://github.com/getsentry/sentry-docs/issues/3056 to properly track the issue, thank you for reporting it.
