### ISSUE TITLE
Option for Rate Limiting

### ISSUE THREAD

**Issue by benr77** [getsentry/sentry-symfony#449]
Hello. How do I set the rate_limit option in my Symfony configuration? 

The docs state the parameter is `system.rate_limit` but I don't know where to set this.

Thank you.

**Comment by stayallive** [comment]
Hi @benr77,

The only place I can find this option is: https://develop.sentry.dev/services/quotas/#system-wide-rate-limiting.

But that is for self-hosted Sentry instances and you opened an issue on the Sentry Symfony integration, are you in the correct place or looking for the correct thing?

The SDK's themselfs have, to the best of my knowledge, no configurable "rate limit".

What is it you are trying to achieve exactly?

**Comment by benr77** [comment]
Thanks for the super quick reply!

I'm not using the self-hosted Sentry but obviously got confused reading about this option in the self-hosted docs.

I have a situation where an error is being thrown on every page request, and if I don't catch it in time (manually) it uses up my entire Sentry quota for the month with thousands of repeats of the same error.

Obviously I do want to log the error, but not the same issue thousands of times. So I was looking for a way to rate limit - ideally just to stop duplicates of the same issue being continuously sent.

I'm using the latest SDK etc on Symfony 4.4.

Any pointers appreciated.

**Comment by stayallive** [comment]
That's a tricky situation, since we are in PHP we have no shared state between all page requests so there is not much possible in terms of rate limiting.

I'm also not sure if you expect that error to occur on each page request or that you mean something broke that happens on each page request and is eating through your limit?

---

In the last case where there is an actual bad thing happening, just on every page request. You could setup some server side limits here: `https://sentry.io/settings/<your org>/rate-limits/` (replace `<your org>` with the name of your org) to prevent blowing through your limits.

---

In the first case you might have to do some more work if you always sent an event to Sentry for every request by design:

The one thing coming to mind is you implement some logic yourself to discard the message once you've seen it with some custom logic and the help of your app's cache or something (just spitballing here).

This is the hook: https://docs.sentry.io/platforms/php/guides/symfony/configuration/options/#before-send.

That hooks expects a callback that looks like this:

```php
function (\Sentry\Event $event): ?\Sentry\Event {
	if (some_logic_to_rate_limit($event)) {
		return null;
	}

	return $event;
}
```

In this you can inspect the `$event` and see what kind of exception we are going to send and if you want to stop it sending because you already know you did or by some other condition you can `return null` from that callback to prevent the issue from being transmitted to Sentry.

---

Hope this helps, let me know if any of it is useful or that I'm misunderstanding the issue.

**Comment by benr77** [comment]
My case is the latter whereby it's NOT by design and it's an uncaught application exception. So I will follow up on setting the server side rate limits as you suggest.

However, thank you for the detailed explanation of how to deal with things locally within the application - that is very useful and I will look in to this for more sophisticated handling going forward.

Thanks again.

**Comment by benr77** [comment]
Just to add to this for posterity, I have found an option called **Spike Protection** which seems to do exactly what I want. I have not tested it yet but seems pretty clear what it does. It's to be found in the Billing section of the Sentry account.

`https://sentry.io/settings/<your org>/billing/overview/`
