### ISSUE TITLE
Utility for printing the meta tag for tracing

### ISSUE THREAD

**Issue by Jean85** [getsentry/sentry-symfony#458]
As reported in https://github.com/getsentry/sentry-php/issues/1192#issuecomment-789709631, to link a PHP tracing transaction to the frontend where you may be using the Sentry JS SDK, 

> You need to connect the PHP traces to the JS SDK by setting a meta tag on your page the JS SDK can read.
> ```
> <meta name="sentry-trace" content="49879feb76c84743ba5034bd2d3f1ca3-7cb5535c930d4666-1"/>
> ```
> Example from Laravel: https://docs.sentry.io/platforms/php/guides/laravel/performance/#connect-your-frontend.
> 
> This is how that header is built: https://github.com/getsentry/sentry-laravel/blob/be9658a57d554f8bfe587facc1492a45c6bd0e1c/src/Sentry/Laravel/Integration.php#L175-L187.

We could provide something similar here in the Symfony bundle; probably a Twig partial which uses a Twig function to retrieve the current transaction id.

**Comment by ste93cry** [comment]
Rather than providing a Twig helper, do we know if adding the sentry-trace header to the HTTP response works? I would say it should, @stayallive do you know anything about this?

**Comment by Jean85** [comment]
That would be a lot better!

**Comment by stayallive** [comment]
It does not because the "initiator" adds that value (indicating to follow up requests the trace ID and if the request is sampled). 

So if PHP is rendering a HTML page it is the initiator the JS SDK cannot read the header from te response (JS has no access to headers from the document request) so it needs that meta tag. 

If JS is the initiator of the request it adds the header to the request to the PHP backend. 

In theory it could also read the header from the PHP response in the last example but I don't believe that happens but I could be wrong.  

But a "simple" helper function like we have in Laravel should also be enough. So it doesn't matter which templating engine you use, all have options to echo unescaped HTML.

**Comment by pbowyer** [comment]
For anyone who wants a copy & paste, this is my code:
```php
<?php

namespace App\Twig;

use Sentry\SentrySdk;
use Twig\TwigFunction;

class AppExtension extends AbstractExtension
{
    public function getFunctions()
    {
        return [
            new TwigFunction('sentryMetaTag', [$this, 'sentryMetaTag']),
        ];
    }

    public function sentryMetaTag()
    {
        $span = SentrySdk::getCurrentHub()->getSpan();

        if ($span === null) {
            return '';
        }

        $content = sprintf('<meta name="sentry-trace" content="%s"/>', $span->toTraceparent());
        // $content .= sprintf('<meta name="sentry-trace-data" content="%s"/>', $span->getDescription());

        return $content;
    }
}
```

with usage in the Twig templates as:
```twig
    {{ sentryMetaTag()|raw }}
```
