### ISSUE TITLE
Recommended way to disable the error handler on a specific route

### ISSUE THREAD

**Issue by VincentLanglet** [getsentry/sentry-symfony#468]
We're using both Symfony and another Framework for our website.

Symfony is the entrypoint, and if the route is not found, it's deledated to the other framework thanks to a custom symfony route. So whenever we have an exception on the other framework, it's reported with the following meta data:
- `route: assurancevie_legacy_default_index`

Is there a way to ignore this route ?
I can add some code in this specific controller if needed.

**Comment by Jean85** [comment]
If not sending error is enough, there are a couple of ways to do it, like using the `before_send` callback and intercepting anything pertaining to that route.

If your issue is the handler itself instead, because maybe it's interfering with the legacy code, that would probably be more complicated... It's another instance where #337 would be the silver bullet.

Probably going through the stack of handlers and unregistering them is the only way to go.

**Comment by VincentLanglet** [comment]
Yes indeed, not sending error is enough.

I tried to make https://github.com/getsentry/sentry-php/pull/1201 :)
