### ISSUE TITLE
Need help: configuration of event for captureEvent

### ISSUE THREAD

**Issue by jokaorgua** [getsentry/sentry-symfony#481]
Hello everyone. I'm trying to understand how to configure event in symfony 5.1* to send it with captureEvent in onKernelException. I know that there is an exception handler in this bundle but I can not find how to send request data in handler (POST,GET,SERVER, etc).

```php
$event = \Sentry\Event::createEvent();
$event->setExceptions(
    [
        new ExceptionDataBag(
            $exception
        ),
    ]
);
$event->setExtra(['POST' => $_POST, 'GET' => $_GET, 'SERVER' => $_SERVER]);
```

this is my current code, everything is ok. but I need also a stracktrace. I've found that stacktrace can be added to ExceptionDataBag, but for building an stacktraceBuilder I need a lot of dependencies.

Maybe there is a simpler way to achieve this? I just need to send an exception with additional data and stacktrace.

Thanks

**Comment by Jean85** [comment]
You're basically rebuilding the wheel a couple times over :smile: let me get you some pointers:
 * for request data, there's the `RequestIntegration` enabled by default; if it's not catching anything, we should check it further; we also provide a `RequestFetcher` in this bundle that helps converting the Symfony request into something usable for that integration
 * the stacktrace is build automatically from the exception if you use `captureException`
 * if you do `captureEvent` or `captureMessage`, the stack trace is present only if you enable the `attach_stacktrace` option; keep in mind that you'll get the wrong trace this way though, because you'll get it from the place from which you're calling the `captureMessage`, not the place from where the error originated

**Comment by jokaorgua** [comment]
@Jean85 thanks a lot for the help. I've started to use your ExceptionListener and have found interesting behavior

When you send a multiform post request with query string and other fields in post data the sentry admin panel does not show the Body and QueryString data. This is what confused me and I've started to make my own solution and re-invent the wheel :)

Is such a thing with files should be or this is a bug?

**Comment by jokaorgua** [comment]
debugged a code a little bit

When in RequestIntegration::captureRequestBody we check the request body and files in request are more than max_request_body_size in config we return null

As for me this is not obvious behavior. Maybe you should consider throwing an warning right in body size or something similar and not just skip the body size?

**Comment by Jean85** [comment]
I'm not sure that I understood... `max_request_body_size` is an option, if the size is `null` it may be due to multiple things, but IIRC we had to fallback to that behaviour due to possible OOM. You can look into https://github.com/getsentry/sentry-php/pull/1139 for more details.
