### ISSUE TITLE
Listener priority on kernel.exception

### ISSUE THREAD

**Issue by tdel** [getsentry/sentry-symfony#49]
Hi, 

Today, i get the exception on sentry even if I catch it from kernel.exception and want to redirect my user instead of seeing it on sentry. 

Can the listener have lower priority on kernel.exception event ? 

What do you think ?

**Comment by Jean85** [comment]
Changing the listener priority could be a bad idea. 

First off, it's a BC change. Secondly, we could become lower of other changes, like the redirection to standard error pages. Third, the easy solution is to make your priority higher.

Lastly, right now it has the default priority (I think it's `0`?) so it's best to leave it like that, IMHO.

**Comment by rdohms** [comment]
I'm currently having issues with this prio as well.

We have a exception converter that wraps all exceptions in a known set, this has to run before a internal Firewall listener that Symfony has, which is set also to `0`. This means it has to be `-1`, which then means it does not run before the sentry listener.

My suggestions (and i'll follow this up with a PR) is to make a priority parameter, so if its set you can configure your own prio, otherwise it defaults to 0, this means no BC and users get flexibility. Is this ok?

**Comment by Jean85** [comment]
Oh yeah that would be an optimal solution, since no BC!
Thanks @rdohms, a PR is more than welcome!
