### ISSUE TITLE
Question: How to deal with Code Mappings in combination with this bundle

### ISSUE THREAD

**Issue by rjd22** [getsentry/sentry-symfony#496]
I hope you will allow to ask me this question because even after digging in all the documentation I cannot find the correct answer for this.

Code Mappings when integrating Sentry with Symfony using this bundle might not work out of the box if you deploy multiple versions of an application you your server.

The reason is that the bundle reports absolute paths by default (I think this is correct behavior) but code mappings don't seem to allow wildcards. Meaning if you deploy your application for example to the following folders you are unable to make a code mapping for it.

```
/var/www/releases/1/
/var/www/releases/2/
/var/www/releases/3/
```
It seems normally a project truncates the path in the event meaning `/var/www/releases/1/src/` becomes `src/`. I think this an okay solution but I'm sad that this way a lot of important information is omitted.

My question is how do others deal with this problem? Are there settings in this bundle that make dealing with this easier?

Relevant documentation:
https://docs.sentry.io/product/integrations/gitlab/#stack-trace-linking

**Comment by Jean85** [comment]
Truncating the paths is useful to eliminate noise, in regards to aggregating the events; having events split due to happening on different servers/paths/releases would be bad, right? It's the opposite side of the spectrum of what you're asking.

If you need to investigate on where an event is happening, you should use the `release` option, which adds a tag with the release currently running when the event occurred. This is a separate piece of information that you can populate at will, and it's not bound to anything specific.

By default, that value uses the `composer.json` version, which normally falls back to the git commit hash. Depending on your deployment strategy, git could be missing and that value could be not useful, but if you populate it correctly, you'll have what you need.

**Comment by rjd22** [comment]
@Jean85 Thank you for your answer! That indeed makes sense. What is the recommended way or truncating the path in combination with the sentry bundle?

**Comment by Jean85** [comment]
> What is the recommended way or truncating the path in combination with the sentry bundle?

It should happen by default thanks to `kernel.project_dir` : https://github.com/getsentry/sentry-symfony/blob/c016dc2496833c73747a5e5babf04c41791a5118/src/DependencyInjection/Configuration.php#L50-L51

**Comment by rjd22** [comment]
@Jean85 thank you for taking the time to answer. This actually was very helpful. I found out the default `prefixes` were added in version 4.x. while still using 3.5 for this project I'm talking about. I will upgrade Sentry to make use of this feature.
