### ISSUE TITLE
Installation of sentry/sentry-symfony package in version 4.1 with symfony/symfony 3.4.x version breaks appliciation due to missing cache contract

### ISSUE THREAD

**Issue by lordrhodos** [getsentry/sentry-symfony#511]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
`"sentry/sentry-symfony": "^4.1",`

### Steps to Reproduce

Installed the above mentioned package with

`composer require sentry/sentry-symfony`

### Expected Result

Application runs as before with an activated sentry integration.

### Actual Result
Application is broken:

![Bildschirmfoto 2021-05-27 um 12 28 09](https://user-images.githubusercontent.com/807902/119811343-49370f00-bee7-11eb-9408-a1547874bd45.jpg)

due to a missing symfony cache interface. The cache Interface used here:

https://github.com/getsentry/sentry-symfony/blob/master/src/Tracing/Cache/TraceableCacheAdapter.php#L11

but the compose.json file is not defining the `symfony/cache` or `symfony/cache-contracts` as required package.

**Comment by ste93cry** [comment]
While it is not correct to require the `symfony/cache` component because the integration is optional, on Symfony `3.4` I didn't noticed before that that package doesn't depend on `symfony/cache-contracts` package. I've opened a PR to fix the issue, if you could try it and let me know if it works it would be great

**Comment by lordrhodos** [comment]
thx @ste93cry for the quick reply and fix :+1:
