### ISSUE TITLE
Allow to get decorated connection

### ISSUE THREAD

**Issue by simPod** [getsentry/sentry-symfony#522]
I was using `Connection::getWrappedConnection()` to get underlying PDO so I can call `pgsqlGetNotify()` etc.

Now there's TracingDriverConnection as a wrapped connection instead. But there's no way to get what's decorated.

So PDO is decorated but I have no longer any access to it.

**Comment by ste93cry** [comment]
Sorry for the extremely late answer: taking for granted that (at least in DBAL `3.x`) the middleware feature has been introduced for the exact purpose of wrapping a driver, I would say that there is nothing we can do here and instead you should ask to fix this somehow in the [`doctrine/dbal`](https://github.com/doctrine/dbal) repo. We already had in the past issues like these, and usually it's because the implementations were not meant (at least initially) to work with the decorator pattern

**Comment by simPod** [comment]
@ste93cry Hi, can you check https://github.com/doctrine/dbal/issues/4705#issuecomment-879574193 and consider adding the method to access wrapped connection? Thanks!

**Comment by ste93cry** [comment]
Sure, no objections from my side. Would you mind submitting a PR?

**Comment by simPod** [comment]
Sure, expect it tomorrow. Thanks.
