### ISSUE TITLE
Sentry is killing my app

### ISSUE THREAD

**Issue by jsivil-venngage** [getsentry/sentry-symfony#585]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
sentry/sentry-symfony "version": "4.2.4"

PHP 7.4 FPM

### Steps to Reproduce

1. Generate DSN for two php projects
2. One project is dying in response time after the free trial ended.
3. If I empty the DSN string it comes back to life.

### Expected Result

The project should not be affected by the response time / unresponsiveness of the logger.

### Actual Result

The project results in timing out requests / being very slow.

I also can't contact support to understand what's wrong with that particular DSN. I can't do anything but disable Sentry and try another provider.

**Comment by ste93cry** [comment]
I don't think that the bundle is the origin of the issue here, but rather the core SDK. Our transport is syncronous, so proably if the server is slow to respond or you're sending a lot of events it makes sense that the timeout is reached. At the moment there aren't alternatives provided out-of-the-box, so the best I can suggest is to implement your own version of the transport which sends events in batch, asyncronously, or whatever is most appropriate for your use case

**Comment by SerethiX** [comment]
I have a similiar issue, it only appeared after upgrading the symfony bundle from 3.5.4 to 4.2.6
Instead of **44 ms** the response times go up to around **4 seconds**

Without the bundle everything works fine and with the old version I get a much better performance, but can't run php 8.1

I profiled my application and there is a lot of time added in the "getClassMetaData" method from doctrine.
Maybe the newer versions are busting caches?

I'll continue debugging tomorrow, maybe I can gather more information on this problem.

**Comment by ste93cry** [comment]
By default tracing is enabled. Please ensure that `sentry.tracing.enabled = false` and see if it can help you

**Comment by SerethiX** [comment]
Tried that already. Set all options to false and verified the settings were correct using the debugger.

No tracing services were set up but the performance was still very bad at arount 3 - 4 seconds

**Comment by ste93cry** [comment]
Maybe your app is logging a lot of errors (or notices, whatever) and sending them is taking time? The transport provided out of the box is syncronous, so it may be the cause of the slowdown

**Comment by SerethiX** [comment]
We are running this setup for 3-4 years now and utilize breadcrumbs, and it has never been slow.
With the 4.2.6 version it's even slow when there is not a single event sent to sentry.

I will test out the intermediates and check if it's from the very first 4.x release or came in a specific version.

**Comment by SerethiX** [comment]
Mhh I guess I found the issue (partly layer 8).
My DSN was outdated and pointed to the old DNS name. This was not an issue with the older 3.x release, as it would only run into timeouts when there was an event to push and since I'm mostly relying on the symfony debug toolbars I never found out that something was wrong.

I dunno what part is causing the delays on every request, but I would highly recommend not to slow down the applications when sentry is not available and there is nothing to log.

I will have a look into this for our application so we change to an async transport. Could explain some performance problems, since we never thought of sentry as highly critical to general API performance.

Thanks for your input @ste93cry ! Much appreciated.

**Comment by ste93cry** [comment]
>I dunno what part is causing the delays on every request, but I would highly recommend not to slow down the applications when sentry is not available and there is nothing to log

Just wondering if you found out the cause of the slow down when there is nothing to log. It should not happen and I cannot think of any reason about what we could do outside of sending the event when needed. Otherwise, I will close this issue as it seems solved.

**Comment by ste93cry** [comment]
I'm closing this as I think the issue was solved. Feel free to reopen if that's not the case

**Comment by coudenysj** [comment]
Yes, working on that. It's a bit hard, because locally there is no issue, but on production (docker container where the slowdown is) it is a bit harder to profile.

**Comment by coudenysj** [comment]
Got profiler running in production (for a little while) and it already showed the following results:
<img width="463" alt="image" src="https://user-images.githubusercontent.com/96260/161118838-6fc3e3d8-3dde-4613-acca-8f9861dff854.png">

Looks like the problem is somewhere in the container.

**Comment by Jean85** [comment]
Are you reporting deprecations to Sentry? Maybe you're triggering some of those there?

**Comment by coudenysj** [comment]
So the problem was caused by Symfony Vault. We fetch the SENTRY_DSN from the vault, and for some reason the accessing/decrypting of the vault files took a very long time.

By decrypting the vault to a local file during deployment, the slowdown was resolved (and thus had nothing to do with Sentry itself).
