### ISSUE TITLE
How do I set the connect timeout and timeout values?

### ISSUE THREAD

**Issue by matthew-gill** [getsentry/sentry-symfony#592]
We're in the process of implementing Sentry for our Symfony app and would like to set some v. conservative timeouts in the event that the Sentry server is unavailable or slow to respond.

I've been able to set

```yml
sentry:
  options:
    send_attempts: 1
```

Which makes a slight bit of difference, but it seems as if the `DEFAULT_HTTP_CONNECT_TIMEOUT` and `DEFAULT_HTTP_TIMEOUT` are hard coded in `vendor/sentry/sentry/src/HttpClient/HttpClientFactory.php
vendor/sentry/sentry/src/HttpClient/HttpClientFactory.php`

Is there a way I'm missing to override this? Perhaps using the `transport` option (but I can't seem to find any documentation for it).

If you have an example of how to use the `transport` option that would be great. Otherwise, I'll try to raise a PR to set these two values by the `option` config.

**Comment by matthew-gill** [comment]
I've now raised both PRs above. I'm not sure if this is the way to do it, if you have a better way (or it's already possible) I'd love to know, thanks!

**Comment by Jean85** [comment]
I thought that this feature was not feasible since it would require handling that setting for each proper client implementation but, since we're already doing it (but with a hard coded value) I think it has its merits. @ste93cry do you agree?

I have some additional thoughts:
 * it's a new feature, so both PRs have to target develop
 * here on Symfony we will need to lock onto that newer `sentry/sentry` package version, or it will break
 * there are some other corrections needed on the PRs, but I'll leave a contextual review there.

Thanks for the contribution!

**Comment by ste93cry** [comment]
@ste93cry do you agree?

Yes, let's do it once for all

**Comment by Jean85** [comment]
Now both PRs are released! Thank you @matthew-gill!
