### ISSUE TITLE
TracingServerInfoAwareDriverConnection does not support accessing the native connection

### ISSUE THREAD

**Issue by gndk** [getsentry/sentry-symfony#620]
### Environment

How do you use Sentry?
sentry.io

Which SDK and version?
doctrine/dbal 3.3.5
sentry/sentry-symfony 4.2.8
symfony/messenger 6.0.8

### Steps to Reproduce

Run Symfony Messenger `bin/console messenger:consume` command to consume messages from Postgres.

### Expected Result

It works.

### Actual Result

```
In Connection.php line 1546:

  [LogicException]
  The driver connection Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingServerInfoAwareDriverConnection does not s
  upport accessing the native connection.


Exception trace:
  at /srv/share/vendor/doctrine/dbal/src/Connection.php:1546
 Doctrine\DBAL\Connection->getNativeConnection() at /srv/share/vendor/symfony/doctrine-messenger/Transport/PostgreSqlConnection.php:74
 Symfony\Component\Messenger\Bridge\Doctrine\Transport\PostgreSqlConnection->get() at /srv/share/vendor/symfony/doctrine-messenger/Transport/DoctrineReceiver.php:49
 Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineReceiver->get() at /srv/share/vendor/symfony/doctrine-messenger/Transport/DoctrineTransport.php:45
 Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineTransport->get() at /srv/share/vendor/symfony/messenger/Worker.php:100
 Symfony\Component\Messenger\Worker->run() at /srv/share/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php:223
 Symfony\Component\Messenger\Command\ConsumeMessagesCommand->execute() at /srv/share/vendor/symfony/console/Command/Command.php:291
 Symfony\Component\Console\Command\Command->run() at /srv/share/vendor/symfony/console/Application.php:1007
 Symfony\Component\Console\Application->doRunCommand() at /srv/share/vendor/symfony/framework-bundle/Console/Application.php:94
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /srv/share/vendor/symfony/console/Application.php:299
 Symfony\Component\Console\Application->doRun() at /srv/share/vendor/symfony/framework-bundle/Console/Application.php:80
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /srv/share/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /srv/share/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:54
 Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run() at /srv/share/vendor/autoload_runtime.php:29
 require_once() at /srv/share/bin/console:11
```

### Solution

Its solved by https://github.com/getsentry/sentry-symfony/commit/28c2b7ad0e761da3d5a09062682a61d208df05ef, which is from 2022/02/14. Are there any blockers that prevent releasing this?

**Comment by Jean85** [comment]
#597 is not released yet because `develop` is for the next minor, that as of this moment is 4.3, and it's not released yet.

@ste93cry can we release it or are we waiting for something else?

**Comment by ste93cry** [comment]
This is not a bug. The `getNativeConnection()` method was added in DBAL version `3.3`, and although failing to implement it is considered a deprecation, the code has to take into account that not all drivers may have such method. I would say that it's Symfony that should handle the exception and fallback to the old `getWrappedConnection()` method, in case.

>can we release it or are we waiting for something else?

Actually, the release is pretty empty because there hasn't been a lot of movement recently on this package to justify it. I will try to merge the remaining things so that we can make a release in the next weeks

**Comment by gndk** [comment]
> I would say that it's Symfony that should handle the exception and fallback to the old getWrappedConnection() method, in case.

Hmm, they are actually doing that: https://github.com/symfony/doctrine-messenger/blob/5.4/Transport/PostgreSqlConnection.php#L73

Maybe its actually a bug on their side. I'll see if I can find something.

**Comment by gndk** [comment]
Your `TracingDriverConnectionInterface` extends `Doctrine\DBAL\Driver\Connection`, which includes the `getNativeConnection()` method:  https://github.com/getsentry/sentry-symfony/blob/master/src/Tracing/Doctrine/DBAL/TracingDriverConnectionInterface.php#L9

Which is why Symfony's `if (method_exists($this->driverConnection, 'getNativeConnection'))` evaluates to true and uses the native connection.

So I would still consider this a bug here. Alternatively you could declare a conflict with `doctrine/dbal^3.3`

**Comment by ste93cry** [comment]
>Which is why Symfony's `if (method_exists($this->driverConnection, 'getNativeConnection'))` evaluates to true and uses the native connection.

First of all, the [`getNativeConnection()`](https://github.com/doctrine/dbal/blob/3.3.0/src/Driver/Connection.php#L11) method defined by Doctrine has been added in a minor version, and to not break compatibility it is declared with a simple `@method` annotation, proving that implementing it is optional, although obviously recommended. Secondly, the name of the variable used in the Symfony source code is at minimum misleading because what it is representing is the DBAL connection, not the driver connection (they are two different things). That's why the `instanceof` check passes: of course the `Connection::getNativeConnection()` method exists, as it's implemented in the DBAL itself. However, the driver is free to not implement it, at least until the next major version 😉 That's why this cannot be considered a bug on our side, but at worst a deprecation that we didn't solve yet (well, we did in the next minor version, which is unreleased)
