### ISSUE TITLE
Feature Request: sentry-trace propagation for Symfony Console applications

### ISSUE THREAD

**Issue by DAcodedBEAT** [getsentry/sentry-symfony#641]
Currently, the [`sentry-trace` HTTP header](https://develop.sentry.dev/sdk/performance/#header-sentry-trace) is used for trace propagation within Sentry, allowing traces from upstream services to continue traces to downstream services.

Why limit trace propagation to just HTTP requests though?

In order to trace anything (web request, shell script, etc.) invoking a Symfony CLI application, `sentry-symfony` could have a similar trace propagation mechanism for Console applications, where the trace is passed to the invoked application and this value would used when setting up the Transaction's context.

_note_: I initially implemented a solution in #638 but this was deemed as potentially unsafe due to modifying the InputOptions for the entire application through a configured `EventListener`.

**Comment by ste93cry** [comment]
I have to say that I don't have any solution in mind that looks good to be implemented in this public project rather than to the project where you have this particular need. The best solution I can come up with is an environment variable, but I have a lot doubts about the fact that we should really support this out-of-the-box. @vladanpaunovic maybe you could discuss this with the rest of the Sentry team and see if there is a similar need in other SDKs?

**Comment by vladanpaunovic** [comment]
@DAcodedBEAT, thanks a lot for the issue and the idea behind it!

The use case you are presenting seems unique to you and not big enough to justify this becoming the initial behaviour of our SDK.

If we see a valid recognition from our community, that this matters to many people, we will happily find a good solution for this.

Until then, I will close this issue.
