### ISSUE TITLE
Feature Request: log the impersonator

### ISSUE THREAD

**Issue by hunhejj** [getsentry/sentry-symfony#642]
It would be helpful if the impersonator's username was also logged as a tag on a request similar to the authenticated user.

**Comment by Jean85** [comment]
Just to be clear, we're talking about this: https://symfony.com/doc/4.4/security/impersonating_user.html

I'm scrolling through the feature, and we would have to handle it in two ways since in 4.3 they changed/deprecated how to get the impersonated user: https://symfony.com/blog/new-in-symfony-4-3-deprecated-the-role-and-switchuserrole-classes

Anyway, happy to accept a PR on this!

**Comment by hunhejj** [comment]
Thanks for adding more context @Jean85. 

I hope I will find some time creating a PR for this, we will see. Meanwhile a question: would you suggest to add the impersonator's username as a tag or as a metadata of the user?

**Comment by Jean85** [comment]
IMHO, we could put it as a tag, since the addition would be done only when a user is actually impersonating another user; the normal user is already a tag on its own.

But I would like more input on this... @ste93cry WDYT?
