### ISSUE TITLE
Uri class not found

### ISSUE THREAD

**Issue by micheh** [getsentry/sentry-symfony#707]
With the release of sentry/sentry 3.17, `guzzlehttp/psr7` is no longer installed when using the Symfony http client.

This is nice, but leads to an error in this package, as `GuzzleHttp\Psr7\Uri` is still used in the `AbstractTraceableHttpClient`:

https://github.com/getsentry/sentry-symfony/blob/bcdbd3d13376473a514c0ec97566b0c7cdc5a1fc/src/Tracing/HttpClient/AbstractTraceableHttpClient.php#L54

Maybe the http client can be updated to allow `nyholm/psr7` as well or this package should explicitly require `guzzlehttp/psr7`?

**Comment by stayallive** [comment]
That was the missing part, sorry I missed that. In any case we should directly depend on `guzzlehttp/psr7` so I've opened #708 to fix that.

But I've also opened #709 since those instructions are outdated, our own `sentry/sdk` metapackage ships with the Symfony HTTP client these days so there is no reason to replace that package anymore (for that purpose). 

So in your case you can remove the `replace` for `sentry/sdk` (and possibly remove the dependency on `pugx/sentry-sdk` if you ever had that) and it should "fix" the issue for you but ofcourse #708 will fix it correctly if `sentry/sdk` is ever being replaced or switches it's PSR7 dependency 👍
