### ISSUE TITLE
branch-alias is out of date

### ISSUE THREAD

**Issue by garak** [getsentry/sentry-symfony#740]
I guess it should point to `4.9.x-dev`, but it's still pointing to `4.6.x-dev`
See attached screenshot from packagist

![Schermata del 2023-06-25 18-22-33](https://github.com/getsentry/sentry-symfony/assets/179866/25295b56-44fc-4ea2-a7f1-321281059767)

**Comment by ste93cry** [comment]
Nice catch! We stopped updating the `composer.json` when @cleptric implemented the Bash script to automate the version bump during releases. Since we also stopped working on multiple minor versions at the same time, I think we can remove the `branch-alias` config as there is no benefit anymore in using it. Does it makes sense?
