### ISSUE TITLE
Added a Monolog handler

### ISSUE THREAD

**Issue by romaricdrigon** [getsentry/sentry-symfony#77]
Hello,

Logging Symfony error is great.
Adding a Monolog handler in this bundle would be great: in our application, we are using Monolog to log business errors all around, we would like to have those sent to Sentry as well.

Having a config parameter to activate that would be great, as a little bit of bootstrapping code is required.

**Comment by Klaitos** [comment]
Need this too

**Comment by Jean85** [comment]
Since Monolog is normally added with the MonologBundle, adding that piece of bootstrapping code could become really complicated, because we would need to check for the MonologBundle precence (and pre-registration!) before adding it.

I would suggest you to use something less complicated, such as https://github.com/facile-it/sentry-psr-log
