### ISSUE TITLE
Release reported as "1.0.0+no-version-set@{no ref"

### ISSUE THREAD

**Issue by cancan101** [getsentry/sentry-symfony#822]
### How do you use Sentry?

Self-hosted / on-premises

### SDK version

4.14.0

### Steps to reproduce

Trigger an error

### Expected result

a clean string, perhaps the git hash.

### Actual result

In JSON payload
```
"release":"1.0.0+no-version-set@{no ref",
```
Perhaps related to: https://github.com/getsentry/sentry-symfony/issues/366
![image](https://github.com/getsentry/sentry-symfony/assets/51059/c976520c-7650-44fa-9d8e-0a631ed6f15f)

**Comment by Jean85** [comment]
This happens when Sentry is not able to automatically detect the version of your codebase (for example because Git is not available) and no value has been provided to manually set it.

**Comment by cancan101** [comment]
But why the mis matches braces?

**Comment by HazAT** [comment]
@cancan101 Can you set the release manually when you init the SDK?
Like @Jean85 mentioned, we try to pick up the hash from Git but it seems not to work correctly for whatever reason

**Comment by HazAT** [comment]
Ah it might just be some small parsing error, probably not relevant.
Does this maybe run on a CI or somewhere and you don't correctly clone/checkout a repo?

Regardless I don't think this is a bug here since we just try to read env and print the string, the workaround is just set the release directly yourself.
