### ISSUE TITLE
Deprecation notice spam on 8.4

### ISSUE THREAD

**Issue by Bilge** [getsentry/sentry-symfony#897]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

4.14.0

### Steps to reproduce

Upgrade to PHP 8.4

### Expected result

No deprecation warnings

### Actual result

>Deprecated: Sentry\SentryBundle\Tracing\Cache\TraceableTagAwareCacheAdapterForV3::get(): Implicitly marking parameter $beta as nullable is deprecated, the explicit nullable type must be used instead

**Comment by cleptric** [comment]
Please update to version [5.1.0](https://github.com/getsentry/sentry-symfony/releases/tag/5.1.0).
Other version won’t be updated to support PHP 8.4.

**Comment by Wirone** [comment]
@cleptric could you reconsider this? I am investigating the possibility of upgrading our app to PHP 8.4 and was already able to prepare Docker build, and initially fix Composer dependencies to install packages, but I see in the Composer's output many deprecation warnings about implicit nullables, many of them are from Sentry Bundle. Upgrading to 5.x is not affordable for us, because we use `sentry.io` only for production (paying client), but we have also Sentry On Premise for dev apps and this instance does not match the `>= v20.6.0` requirement. Our admins said they don't want to upgrade this instance, so we're somehow blocked. Yes, we can replace Sentry's dev instance with [GlitchTip](https://glitchtip.com/), but to be honest I don't understand why this package's `4.x` branch can't be updated so it does not trigger deprecations on PHP 8.4. These changes are easy, and are not BC-breaks. **I can prepare the PR** if you're open to merge it and release fix version with it. Enforcing people to bump major version that introduces BC-breaks (also on infra level) is a bit harsh.

**Comment by cleptric** [comment]
Given that 5.x has been released almost a year ago, I won't make any more updates to 4.x, besides maybe addressing very critical security issues.
I understand why you can't go to 5.x easily, so maybe using a 4.x fork with your changes could be a good compromise?

**Comment by Wirone** [comment]
Thanks @cleptric for your response. We will discuss the solution based on fork and hopefully will overcome this obstacle.
